spring:
  application:
    name: spring-cloud-eureka


server:
  port: 8000

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url: http://localhost:${server.port}/eureka
